### ISSUE TITLE
history module not found in package.json

### ISSUE THREAD

**Issue by RaulTsc** [liviuignat/heimdall#28]
Not sure how `yarn install` works. Maybe because it is cached in `yarn.lock`, but it definitely needs to be includede as a dependency in `package.json` aswell.

Used in `LanguageLink.test.tsx`

`import {createMemoryHistory} from 'history';`

Also in `client.tsx`

`import {createHistory} from 'history';`

Am I missing something?

**Comment by liviuignat** [comment]
This is weird ... I see history in the `node_modules` too and I think it's being added by some dependency. PS: the name of the Author is funny.

```  
  "name": "history",
  "version": "3.2.1",
  "description": "Manage browser history with JavaScript",
  "repository": "mjackson/history",
  "author": "Michael Jackson",
  "license": "MIT",
```

**Comment by RaulTsc** [comment]
:). Yeah. Most likely. I can see it in `yarn.lock` and running `yarn add bla` adds it to `package.json` by default.

**Comment by liviuignat** [comment]
Ok, I will added directly in `develop`.
